FROM node:4

# Setup PATH to prioritize local npm bin ahead of system PATH.
ENV PATH node_modules/.bin:$PATH

RUN mkdir nid
WORKDIR nid

COPY package.json /nid/
RUN npm install

COPY echo.js /nid/
ENTRYPOINT node echo.js